export default {
  products: [
    {
      name: "slim shorts",
      category: "Shirts",
      image: "/img/bb.jpg",
      price: 60,
      brand: "ary",
      rating: 3.6,
      numReviews: 10,
    },
    {
      name: "Fit shorts",
      category: "Shirts",
      image: "/img/sweater.jpg",
      price: 110,
      brand: "Fitty",
      rating: 2.6,
      numReviews: 6,
    },
    {
      name: "Sweater",
      category: "Pants",
      image: "/img/thin.jpg",
      price: 80,
      brand: "closs",
      rating: 4.6,
      numReviews: 8,
    },
    {
      name: "hard sweater",
      category: "Pants",
      image: "/img/sweeter.jpg",
      price: 80,
      brand: "nicer",
      rating: 4.6,
      numReviews: 8,
    },
    {
      name: "Dress",
      category: "Pants",
      image: "/img/sweet.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.6,
      numReviews: 8,
    },
    {
      name: "light sweater",
      category: "Pants",
      image: "/img/side.jpg",
      price: 80,
      brand: "cools",
      rating: 4.6,
      numReviews: 8,
    },
  ],
};
